server:
  port: 10014

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/testmb2?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: fenli23.
    driver-class-name:  com.mysql.jdbc.Driver
  mvc:
    date-format: yyyy-MM-dd #接受日期格式设置
  profiles:
    active: develop

mybatis:
  mapper-locations: mapping/*Mapper.xml
  type-aliases-package: com.study.yoe.entity

#logging:
#  level:
#    root :  debug
#  file:
#    path: ./log-debug.log